name: Auto-update

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin main

      - name: Push changes
        run: git push origin HEAD:main
